[build]
  base = "frontend"                     
  command = "npm install && ng build --configuration production"
  publish = "dist/frontend/browser"   

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
