-- CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- CREATE TABLE IF NOT EXISTS agent_settings (
--     setting_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     agent_id UUID NOT NULL,
--     dark_mode BOOLEAN DEFAULT FALSE,
--     email_notifications BOOLEAN DEFAULT TRUE,
--     sms_notifications BOOLEAN DEFAULT TRUE,
--     whatsapp_notifications BOOLEAN DEFAULT TRUE,
--     push_notifications BOOLEAN DEFAULT TRUE,
--     sound_enabled BOOLEAN DEFAULT TRUE,
--     created_date TIMESTAMPTZ DEFAULT NOW(),
--     modified_date TIMESTAMPTZ DEFAULT NOW(),
--     CONSTRAINT fk_agent FOREIGN KEY (agent_id) 
--         REFERENCES agent(agent_id) 
--         ON DELETE CASCADE
-- );
