@baseUrl = http://localhost:3000/api/autocomplete
### SAMPLE IDS (replace with real IDs from DB)
@agentId = 7b407c2d-3145-40b0-8c47-1d6f62351b2c
@clientId = ba849305-c1d6-49b6-8494-6666d732e70a
@policyId = 74768c18-6361-49ab-9f64-f96bfb7cea77
@policyCatalogId = 4fb38416-b9dd-419f-8941-72e33288e52c
@templateId = 9dea0892-a05f-4653-bf0c-da7d0fda4772
@typeId = 62669a47-f783-4259-88a7-66a4695fc1fc
@companyId = 1eb437a2-2981-48f6-bfad-e7b7f9b02e2f
@categoryId = 3e97ac8c-0659-4273-b452-f40c62dd8f7a

### STATIC AUTOCOMPLETES

### Get active insurance companies
GET {{baseUrl}}/companies

### Get active policy types
GET {{baseUrl}}/types

### Get active policy categories
GET {{baseUrl}}/categories


### DYNAMIC AUTOCOMPLETES

### Get policy catalog (with optional filters)
GET {{baseUrl}}/catalog?agentId={{agentId}}&companyId={{companyId}}&typeId={{typeId}}&searchTerm=co

### Get policy templates (with optional filters)
GET {{baseUrl}}/templates?agentId={{agentId}}&typeId={{typeId}}&categoryId={{categoryId}}&searchTerm=s

### Get client policies (with optional filters)
GET {{baseUrl}}/client-policies?clientId={{clientId}}&searchTerm=


